### ISSUE TITLE
JsonTelegramParser breaks with KeyError "messages"

### ISSUE THREAD

**Issue by Poolitzer** [joweich/chat-miner#26]
Not sure how your export is formatted, mine has chats => list (which is an actual list) => dict again with type, name and then messages as key... And then the same with left_chats.

**Comment by joweich** [comment]
@Poolitzer this might be solved with #31.
Would you mind adding the error trace and the formatting of your messages in the log?

**Comment by galatolofederico** [comment]
The structure of a JSON export is like that:

```

**Comment by galatolofederico** [comment]
The structure of a JSON export is like this:
```
[federico@thinkpad chat-miner]$ cat export.json | jq  "keys[]"
"about"
"chats"
"contacts"
"frequent_contacts"
"left_chats"
"personal_information"
"profile_pictures"
[federico@thinkpad chat-miner]$ cat export.json | jq  ".chats | keys[]"
"about"
"list"
[federico@thinkpad chat-miner]$ cat export.json | jq  ".chats | .list | .[0] | keys[]"
"id"
"messages"
"name"
"type"
[federico@thinkpad chat-miner]$ 
```

So you have to manually extract `export["chats"]["list"][ID]` in order to use the `JsonTelegramParser`
Maybe it can be an idea to add to the `JsonTelegramParser` `__init__` the `id` of the chat to parse and let the parser do the work

**Comment by joweich** [comment]
@galatolofederico we should definitely go with your proposal. Might be the case that they adapted the JSON structure since @joaoaab implemented this parser

**Comment by joweich** [comment]
This is the format of the export for me:
```
{
 "name": "chatname",
 "type": "personal_chat",
 "id": 12345,
 "messages": [
   {
   "id": 4203,
   "type": "message",
   "date": "2021-11-10T20:37:03",
   "date_unixtime": "1636573023",
   "from": "author1",
   "from_id": "user12345",
   "text": "example",
   "text_entities": [
    {
     "type": "plain",
     "text": "example"
    }
   ]
  },
  {
   "id": 4204,
   "type": "message",
   "date": "2021-11-10T20:52:40",
   "date_unixtime": "1636573960",
   "from": "author2",
   "from_id": "user54321",
   "text": "example",
   "text_entities": [
    {
     "type": "plain",
     "text": "example"
    }
   ]
  }
 ] 
}
```

The current implementation does not throw an error when parsing this log. The resulting dataframe looks fine. I will therefore close this issue for now.

**Comment by massimopavoni** [comment]
I have the same issue, trying to parse the `result.json`:

```python
>>> parser = TelegramJsonParser("DataExport_2022-12-08/result.json")
08.12.2022 11:41:59 INFO     
            Depending on the platform, the message format in chat logs might not be
            standardized accross devices/versions/localization and might change over
            time. Please report issues including your message format via GitHub.
            
08.12.2022 11:41:59 INFO     Initialized parser.
08.12.2022 11:41:59 INFO     Starting reading raw messages into memory...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damax/.local/lib/python3.10/site-packages/chatminer/chatparsers.py", line 38, in __init__
    self._read_file_into_list()
  File "/home/damax/.local/lib/python3.10/site-packages/chatminer/chatparsers.py", line 234, in _read_file_into_list
    self.messages = json_objects["messages"]
KeyError: 'messages'
>>> 
```

Taking a quick look at the file, it seems to me that the `TelegramJsonParser` expects to find a `messages` key in the root of the `result.json` file, but this is not right, as that key is only found within the `chats` objects, under `list`, inside the root.

**Comment by massimopavoni** [comment]
This:

```python
with open('result.json', 'r') as file:
    telegram_data = json.load(file)
with open('selected_chat.json', 'w') as file:
    json.dump(telegram_data['chats']['list'][1], file) # 1 for first chat after saved messages, as I have them pinned that way
parser = TelegramJsonParser('selected_chat.json')
```

Does work (for the one selected chat):

```
08.12.2022 12:01:24 INFO     
            Depending on the platform, the message format in chat logs might not be
            standardized accross devices/versions/localization and might change over
            time. Please report issues including your message format via GitHub.
            
08.12.2022 12:01:24 INFO     Initialized parser.
08.12.2022 12:01:24 INFO     Starting reading raw messages into memory...
08.12.2022 12:01:25 INFO     Finished reading X raw messages into memory.
```
